# CMake generated Testfile for 
# Source directory: /home/runner/work/uncrustify/uncrustify/tests
# Build directory: /home/runner/work/uncrustify/uncrustify/_codeql_build_dir/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(c-sharp "/usr/bin/python3.12" "run_format_tests.py" "c-sharp" "--executable" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/uncrustify" "-d" "--git" "/usr/bin/git" "--result-dir" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/tests")
set_tests_properties(c-sharp PROPERTIES  WORKING_DIRECTORY "/home/runner/work/uncrustify/uncrustify/tests" _BACKTRACE_TRIPLES "/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;49;add_test;/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;0;")
add_test(c "/usr/bin/python3.12" "run_format_tests.py" "c" "--executable" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/uncrustify" "-d" "--git" "/usr/bin/git" "--result-dir" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/tests")
set_tests_properties(c PROPERTIES  WORKING_DIRECTORY "/home/runner/work/uncrustify/uncrustify/tests" _BACKTRACE_TRIPLES "/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;49;add_test;/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;0;")
add_test(cpp "/usr/bin/python3.12" "run_format_tests.py" "cpp" "--executable" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/uncrustify" "-d" "--git" "/usr/bin/git" "--result-dir" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/tests")
set_tests_properties(cpp PROPERTIES  WORKING_DIRECTORY "/home/runner/work/uncrustify/uncrustify/tests" _BACKTRACE_TRIPLES "/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;49;add_test;/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;0;")
add_test(d "/usr/bin/python3.12" "run_format_tests.py" "d" "--executable" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/uncrustify" "-d" "--git" "/usr/bin/git" "--result-dir" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/tests")
set_tests_properties(d PROPERTIES  WORKING_DIRECTORY "/home/runner/work/uncrustify/uncrustify/tests" _BACKTRACE_TRIPLES "/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;49;add_test;/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;0;")
add_test(ecma "/usr/bin/python3.12" "run_format_tests.py" "ecma" "--executable" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/uncrustify" "-d" "--git" "/usr/bin/git" "--result-dir" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/tests")
set_tests_properties(ecma PROPERTIES  WORKING_DIRECTORY "/home/runner/work/uncrustify/uncrustify/tests" _BACKTRACE_TRIPLES "/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;49;add_test;/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;0;")
add_test(imported "/usr/bin/python3.12" "run_format_tests.py" "imported" "--executable" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/uncrustify" "-d" "--git" "/usr/bin/git" "--result-dir" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/tests")
set_tests_properties(imported PROPERTIES  WORKING_DIRECTORY "/home/runner/work/uncrustify/uncrustify/tests" _BACKTRACE_TRIPLES "/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;49;add_test;/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;0;")
add_test(java "/usr/bin/python3.12" "run_format_tests.py" "java" "--executable" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/uncrustify" "-d" "--git" "/usr/bin/git" "--result-dir" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/tests")
set_tests_properties(java PROPERTIES  WORKING_DIRECTORY "/home/runner/work/uncrustify/uncrustify/tests" _BACKTRACE_TRIPLES "/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;49;add_test;/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;0;")
add_test(objective-c "/usr/bin/python3.12" "run_format_tests.py" "objective-c" "--executable" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/uncrustify" "-d" "--git" "/usr/bin/git" "--result-dir" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/tests")
set_tests_properties(objective-c PROPERTIES  WORKING_DIRECTORY "/home/runner/work/uncrustify/uncrustify/tests" _BACKTRACE_TRIPLES "/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;49;add_test;/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;0;")
add_test(pawn "/usr/bin/python3.12" "run_format_tests.py" "pawn" "--executable" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/uncrustify" "-d" "--git" "/usr/bin/git" "--result-dir" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/tests")
set_tests_properties(pawn PROPERTIES  WORKING_DIRECTORY "/home/runner/work/uncrustify/uncrustify/tests" _BACKTRACE_TRIPLES "/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;49;add_test;/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;0;")
add_test(vala "/usr/bin/python3.12" "run_format_tests.py" "vala" "--executable" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/uncrustify" "-d" "--git" "/usr/bin/git" "--result-dir" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/tests")
set_tests_properties(vala PROPERTIES  WORKING_DIRECTORY "/home/runner/work/uncrustify/uncrustify/tests" _BACKTRACE_TRIPLES "/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;49;add_test;/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;0;")
add_test(staging "/usr/bin/python3.12" "run_format_tests.py" "staging" "--executable" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/uncrustify" "-d" "--git" "/usr/bin/git" "--result-dir" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/tests")
set_tests_properties(staging PROPERTIES  WORKING_DIRECTORY "/home/runner/work/uncrustify/uncrustify/tests" _BACKTRACE_TRIPLES "/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;49;add_test;/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;0;")
add_test(sources_format "/usr/bin/python3.12" "run_sources_tests.py" "--executable" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/uncrustify" "-d" "--git" "/usr/bin/git" "--result-dir" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/tests")
set_tests_properties(sources_format PROPERTIES  WORKING_DIRECTORY "/home/runner/work/uncrustify/uncrustify/tests" _BACKTRACE_TRIPLES "/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;60;add_test;/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;0;")
add_test(cli_options "/usr/bin/python3.12" "test_cli_options.py" "--config" "Release" "--build" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir" "--diff" "--test" "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/tests/cli")
set_tests_properties(cli_options PROPERTIES  WORKING_DIRECTORY "/home/runner/work/uncrustify/uncrustify/tests/cli" _BACKTRACE_TRIPLES "/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;70;add_test;/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;0;")
add_test(sanity "/home/runner/work/uncrustify/uncrustify/_codeql_build_dir/uncrustify" "--help")
set_tests_properties(sanity PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;93;add_test;/home/runner/work/uncrustify/uncrustify/tests/CMakeLists.txt;0;")
